/* Syna UI bitmap subset derived from Noto Sans CJK SC.
 * Font data licensed under SIL OFL 1.1; see assets/fonts/SOURCE.md and licenses.
 * Generated by assets/generate_ui_fonts.py. Preserve upstream font attribution.
 */
#include "lvgl.h"
extern const lv_font_t ui_font_11_regular;
static const uint8_t bitmap[] = {
    0xff, 0x80, 0x00, 0x00, 0x00, 0x10, 0x08, 0x04, 0x03, 0xe7, 0x00, 0x80, 0x40, 0x22, 0x1f, 0x00,
    0x7f, 0x00, 0x00, 0x07, 0xc0, 0x00, 0x01, 0xfc, 0x10, 0x08, 0x1f, 0x82, 0x41, 0x21, 0x10, 0x88,
    0x45, 0xc3, 0x80, 0x00, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xfe, 0x7f, 0x08, 0x04, 0x07,
    0xc1, 0x20, 0x90, 0x49, 0xff, 0x04, 0x12, 0x09, 0x04, 0x42, 0x22, 0x11, 0x04, 0x00, 0x08, 0x04,
    0x3f, 0xe0, 0x01, 0x41, 0x10, 0x88, 0x82, 0x80, 0x80, 0x00, 0x00, 0x40, 0x17, 0xb9, 0x44, 0xa3,
    0x53, 0x49, 0x24, 0x92, 0x53, 0x00, 0x00, 0x00, 0x08, 0x04, 0x02, 0x01, 0x0f, 0xf8, 0x40, 0x20,
    0x10, 0x08, 0x00, 0x00, 0x00, 0x08, 0x25, 0x12, 0x9f, 0xf4, 0xa2, 0x51, 0x28, 0x94, 0x8a, 0x00,
    0x00, 0x7f, 0x2a, 0x95, 0x4a, 0xa6, 0x72, 0x09, 0xfc, 0x02, 0x22, 0x11, 0x3f, 0xe4, 0x42, 0x21,
    0x10, 0x88, 0x7c, 0x22, 0x00, 0x00, 0x00,
};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {
    {0},
    {.bitmap_index=0, .adv_w=144, .box_w=9, .box_h=4, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=5, .adv_w=144, .box_w=9, .box_h=9, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=16, .adv_w=144, .box_w=9, .box_h=7, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=24, .adv_w=144, .box_w=9, .box_h=10, .ofs_x=0, .ofs_y=-2},
    {.bitmap_index=36, .adv_w=144, .box_w=9, .box_h=7, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=44, .adv_w=144, .box_w=9, .box_h=8, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=53, .adv_w=144, .box_w=9, .box_h=8, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=62, .adv_w=144, .box_w=9, .box_h=11, .ofs_x=0, .ofs_y=-2},
    {.bitmap_index=75, .adv_w=144, .box_w=9, .box_h=11, .ofs_x=0, .ofs_y=-2},
    {.bitmap_index=88, .adv_w=144, .box_w=9, .box_h=11, .ofs_x=0, .ofs_y=-2},
    {.bitmap_index=101, .adv_w=144, .box_w=9, .box_h=10, .ofs_x=0, .ofs_y=-2},
    {.bitmap_index=113, .adv_w=144, .box_w=9, .box_h=8, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=122, .adv_w=144, .box_w=9, .box_h=11, .ofs_x=0, .ofs_y=-2},
};
static const uint16_t unicode_list[] = {
    0, 3, 9, 93, 140, 148, 875, 877, 1053, 1345, 1349, 2267, 4351,
};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{.range_start=19968, .range_length=4352, .glyph_id_start=1, .unicode_list=unicode_list, .list_length=13, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc = {.glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=1, .bitmap_format=LV_FONT_FMT_TXT_PLAIN};
const lv_font_t ui_font_9_cjk = {.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height=12, .base_line=3, .subpx=LV_FONT_SUBPX_NONE, .underline_thickness=1, .fallback=&ui_font_11_regular, .dsc=&dsc};
