/* Syna UI bitmap subset derived from Noto Sans CJK SC.
 * Font data licensed under SIL OFL 1.1; see assets/fonts/SOURCE.md and licenses.
 * Generated by assets/generate_ui_fonts.py. Preserve upstream font attribution.
 */
#include "lvgl.h"
extern const lv_font_t ui_font_11_regular;
static const uint8_t bitmap[] = {
    0xff, 0xe0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f, 0xc0, 0x00, 0x00, 0x00, 0x03, 0xf8, 0x00, 0x00,
    0x00, 0x00, 0x7f, 0xc0, 0x3f, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xfe, 0x7f,
    0xc1, 0x00, 0x20, 0x04, 0x03, 0xf8, 0x12, 0x02, 0x40, 0x88, 0x7f, 0xc0, 0x04, 0x00, 0x80, 0x10,
    0x3f, 0xe0, 0x00, 0x22, 0x04, 0x41, 0x04, 0x20, 0x88, 0x09, 0x01, 0x00, 0x7f, 0xc9, 0x49, 0x29,
    0x25, 0x25, 0x24, 0xa7, 0x98, 0x12, 0x02, 0x7f, 0xc8, 0x08, 0x3f, 0x84, 0x10, 0x82, 0x10, 0x43,
    0xf8, 0x41, 0x08, 0x21, 0x04, 0x3f, 0x84, 0x10,
};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {
    {0},
    {.bitmap_index=0, .adv_w=176, .box_w=11, .box_h=5, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=7, .adv_w=176, .box_w=11, .box_h=9, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=20, .adv_w=176, .box_w=11, .box_h=8, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=31, .adv_w=176, .box_w=11, .box_h=9, .ofs_x=0, .ofs_y=0},
    {.bitmap_index=44, .adv_w=176, .box_w=11, .box_h=11, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=60, .adv_w=176, .box_w=11, .box_h=10, .ofs_x=0, .ofs_y=-1},
    {.bitmap_index=74, .adv_w=176, .box_w=11, .box_h=10, .ofs_x=0, .ofs_y=-1},
};
static const uint16_t unicode_list[] = {
    0, 9, 140, 148, 877, 2267, 6117,
};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{.range_start=19968, .range_length=6118, .glyph_id_start=1, .unicode_list=unicode_list, .list_length=7, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc = {.glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=1, .bitmap_format=LV_FONT_FMT_TXT_PLAIN};
const lv_font_t ui_font_11_cjk = {.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height=14, .base_line=3, .subpx=LV_FONT_SUBPX_NONE, .underline_thickness=1, .fallback=&ui_font_11_regular, .dsc=&dsc};
